"""Parser for official BOAT RACE program text files."""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd


FULL_WIDTH_TRANSLATION = str.maketrans(
    "０１２３４５６７８９Ｒ",
        "0123456789R",
        )

        PROGRAM_PATTERN = re.compile(
            r"^(?P<boat_no>[1-6])\s"
                r"(?P<racer_id>\d{4})"
                    r"(?P<racer_name>.{4})"
                        r"(?P<age>\d{2})"
                            r"(?P<branch>.{2})"
                                r"(?P<weight_kg>\d{2})"
                                    r"(?P<class>[AB][12])\s*"
                                        r"(?P<national_win_rate>\d\.\d{2})\s*"
                                            r"(?P<national_place2_rate_pct>\d{1,3}\.\d{2})\s*"
                                                r"(?P<local_win_rate>\d\.\d{2})\s*"
                                                    r"(?P<local_place2_rate_pct>\d{1,3}\.\d{2})\s*"
                                                        r"(?P<motor_no>\d{1,2})\s*"
                                                            r"(?P<motor_place2_rate_pct>\d{1,3}\.\d{2})\s*"
                                                                r"(?P<boat_no_equipment>\d{1,2})\s*"
                                                                    r"(?P<boat_place2_rate_pct>\d{1,3}\.\d{2})"
                                                                        r"(?P<series_results_raw>.*)$"
                                                                        )

                                                                        KEY_COLUMNS = [
                                                                            "race_date",
                                                                                "venue_code",
                                                                                    "race_no",
                                                                                        "boat_no",
                                                                                            "racer_id",
                                                                                            ]


                                                                                            def normalize_name(value: str) -> str:
                                                                                                """Remove regular and full-width spaces from a racer name."""
                                                                                                    return str(value).replace("　", "").replace(" ", "").strip()


                                                                                                    def parse_program_text(
                                                                                                        text: str,
                                                                                                            race_date: str,
                                                                                                                source_file: str = "",
                                                                                                                ) -> pd.DataFrame:
                                                                                                                    """Parse decoded official program text into one row per race entry."""
                                                                                                                        normalized_date = pd.Timestamp(race_date).date().isoformat()
                                                                                                                            records: list[dict[str, object]] = []
                                                                                                                                unmatched: list[str] = []

                                                                                                                                    venue_code: str | None = None
                                                                                                                                        race_no: int | None = None

                                                                                                                                            for line in text.splitlines():
                                                                                                                                                    venue_match = re.match(r"^(\d{2})BBGN$", line.strip())

                                                                                                                                                            if venue_match:
                                                                                                                                                                        venue_code = venue_match.group(1)
                                                                                                                                                                                    race_no = None
                                                                                                                                                                                                continue

                                                                                                                                                                                                        normalized_line = line.translate(FULL_WIDTH_TRANSLATION)
                                                                                                                                                                                                                race_match = re.match(r"^\s*(\d{1,2})R\s", normalized_line)

                                                                                                                                                                                                                        if race_match and "電話投票締切予定" in line:
                                                                                                                                                                                                                                    race_no = int(race_match.group(1))
                                                                                                                                                                                                                                                continue

                                                                                                                                                                                                                                                        if not re.match(r"^[1-6]\s\d{4}", line):
                                                                                                                                                                                                                                                                    continue

                                                                                                                                                                                                                                                                            if venue_code is None or race_no is None:
                                                                                                                                                                                                                                                                                        unmatched.append(line)
                                                                                                                                                                                                                                                                                                    continue

                                                                                                                                                                                                                                                                                                            entry_match = PROGRAM_PATTERN.match(line)

                                                                                                                                                                                                                                                                                                                    if not entry_match:
                                                                                                                                                                                                                                                                                                                                unmatched.append(line)
                                                                                                                                                                                                                                                                                                                                            continue

                                                                                                                                                                                                                                                                                                                                                    values = entry_match.groupdict()

                                                                                                                                                                                                                                                                                                                                                            records.append(
                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                        "race_date": normalized_date,
                                                                                                                                                                                                                                                                                                                                                                                                        "venue_code": venue_code,
                                                                                                                                                                                                                                                                                                                                                                                                                        "race_no": race_no,
                                                                                                                                                                                                                                                                                                                                                                                                                                        "boat_no": int(values["boat_no"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "racer_id": values["racer_id"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "racer_name": normalize_name(values["racer_name"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "age": int(values["age"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "branch": values["branch"].strip(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "weight_kg": int(values["weight_kg"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "class": values["class"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "national_win_rate": float(values["national_win_rate"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "national_place2_rate_pct": float(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            values["national_place2_rate_pct"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "local_win_rate": float(values["local_win_rate"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "local_place2_rate_pct": float(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                values["local_place2_rate_pct"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "motor_no": int(values["motor_no"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "motor_place2_rate_pct": float(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    values["motor_place2_rate_pct"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "boat_no_equipment": int(values["boat_no_equipment"]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "boat_place2_rate_pct": float(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        values["boat_place2_rate_pct"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "series_results_raw": values["series_results_raw"].strip(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "source_file": source_file,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if unmatched:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        preview = "\n".join(repr(line) for line in unmatched[:20])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f"Unparsed program lines: {len(unmatched)}\n{preview}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dataframe = pd.DataFrame.from_records(records)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if dataframe.empty:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise ValueError("No program entries were parsed")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duplicate_count = int(dataframe.duplicated(KEY_COLUMNS).sum())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if duplicate_count:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise ValueError(f"Duplicate program keys: {duplicate_count}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        invalid_races = int(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dataframe.groupby(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ["race_date", "venue_code", "race_no"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ).size()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    != 6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).sum()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if invalid_races:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"Program races without six entries: {invalid_races}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return dataframe


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def parse_program_file(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        path: str | Path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            race_date: str,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                encoding: str = "cp932",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) -> pd.DataFrame:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Read and parse an official program TXT file."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        source_path = Path(path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text = source_path.read_bytes().decode(encoding, errors="strict")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return parse_program_text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text=text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                race_date=race_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        source_file=source_path.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            